/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeCall {
  /**
   * Join as an SFU participant. The user token is minted inside the Rust
   * core from the server secret and refreshed there for the join's lifetime.
   */
  join(optionsJson: string): Promise<undefined>
  /**
   * Leave the call and tear down both PeerConnections. Safe from any state,
   * including mid-join, and resolves every pending native read.
   */
  leave(): Promise<undefined>
  /**
   * The authoritative `RtcCallStateSnapshot`, as JSON.
   *
   * Asynchronous because the live session id lives behind the connection
   * lock; the Node side caches the result so `call.state` stays synchronous.
   */
  stateJson(): Promise<string>
  /** A publisher/subscriber `getStats` snapshot, or `None` when disconnected. */
  statsJson(): Promise<string | null>
  /**
   * Await the next call event as JSON, or `None` once the stream closes.
   *
   * A subscriber that falls behind the broadcast buffer receives a synthetic
   * `queueOverflow` event rather than a silent gap.
   */
  nextEvent(): Promise<string | null>
  /** Await the next inbound remote track, or `None` once the call is gone. */
  nextRemoteTrack(): Promise<NativeRemoteTrack | null>
  /**
   * Ask the call owner for additional capabilities. Observable by other
   * participants as a coordinator `call.permission_request` event.
   */
  requestPermissions(permissions: Array<string>): Promise<string>
  /** Maximum reconnect duration. Zero reconnects indefinitely. */
  setDisconnectionTimeout(timeoutSeconds: number): void
  /** Publishing preferences for the next join generation. */
  updatePublishOptions(preferredVideoCodec?: string | undefined | null): void
  /**
   * Coarse subscription policy applied to every remote participant. The SFU
   * forwards no media until this runs; the default policy is audio-only.
   */
  updateSubscriptions(configJson: string): Promise<undefined>
  /** Subscribe to an exact set of participant-session tracks. */
  updateSubscriptionTargets(targetsJson: string): Promise<undefined>
  /** Enable or disable incoming video from every remote participant. */
  setIncomingVideoEnabled(enabled: boolean): Promise<undefined>
  publishAudio(track: NativeLocalAudioTrack): Promise<undefined>
  publishVideo(track: NativeLocalVideoTrack): Promise<undefined>
  publishScreenShare(track: NativeLocalVideoTrack): Promise<undefined>
  publishScreenShareAudio(track: NativeLocalAudioTrack): Promise<undefined>
  /**
   * Stop an audio publication. `trackType` distinguishes microphone audio
   * from screen-share audio.
   */
  stopPublishAudio(track: NativeLocalAudioTrack, trackType: string): Promise<undefined>
  /** Stop a video publication as either camera video or screen share. */
  stopPublishVideo(track: NativeLocalVideoTrack, trackType: string): Promise<undefined>
  muteTrack(trackType: string): Promise<undefined>
  unmuteTrack(trackType: string): Promise<undefined>
  startNoiseCancellation(): Promise<undefined>
  stopNoiseCancellation(): Promise<undefined>
}

export declare class NativeLocalAudioTrack {
  static opus(): NativeLocalAudioTrack
  writePcm(data: Buffer, sampleRate: number, channels: number): Promise<undefined>
  writeEncoded(data: Buffer, durationMs: number, audioLevel?: number | undefined | null): Promise<undefined>
  writeRtp(packet: NativeRtpPacket, audioLevel?: number | undefined | null): Promise<undefined>
  flush(): void
}

export declare class NativeLocalVideoTrack {
  static vp8(optionsJson?: string | undefined | null): NativeLocalVideoTrack
  static vp9(optionsJson?: string | undefined | null): NativeLocalVideoTrack
  static h264(optionsJson?: string | undefined | null): NativeLocalVideoTrack
  writeI420(data: Buffer, width: number, height: number, durationMs: number): Promise<undefined>
  writeEncoded(data: Buffer, durationMs: number): Promise<undefined>
  writeRtp(packet: NativeRtpPacket): Promise<undefined>
}

export declare class NativeRemoteTrack {
  get userId(): string
  get sessionId(): string
  get trackLookupPrefix(): string
  get trackType(): string
  get mimeType(): string
  get payloadType(): number
  get clockRate(): number
  get channels(): number
  get ssrc(): number
  nextPcm(): Promise<NativePcmFrame | null>
  nextVideoFrame(): Promise<NativeVideoFrame | null>
  readRtp(): Promise<NativeRtpPacket | null>
  drainRtp(): Promise<boolean>
  requestKeyframe(): Promise<void>
}

export declare class NativeStreamClient {
  /**
   * Build a server-authenticated client. Tokens for the participant path are
   * minted inside the Rust core, so the secret never reaches JavaScript's
   * media path.
   */
  constructor(apiKey: string, apiSecret: string, baseUrl?: string | undefined | null)
  /** A handle to one call. Cheap: no request is made until the call is joined. */
  call(callType: string, id: string): NativeCall
}

/**
 * Version of the contract between this addon and the Node SDK's loader.
 *
 * The SDK refuses to construct a call when this does not match the version it
 * was built against, so bump it on any breaking change to the native surface.
 */
export declare function bindingApiVersion(): number

export interface NativePcmFrame {
  data: Buffer
  sampleRate: number
  channels: number
  durationMs: number
}

export interface NativeRtpExtension {
  id: number
  payload: Buffer
}

export interface NativeRtpPacket {
  version: number
  padding: boolean
  extension: boolean
  marker: boolean
  payloadType: number
  sequenceNumber: number
  timestamp: number
  ssrc: number
  csrc: Array<number>
  extensionProfile: number
  extensions: Array<NativeRtpExtension>
  extensionsPadding: number
  payload: Buffer
}

export interface NativeVideoFrame {
  data: Buffer
  width: number
  height: number
  rtpTimestamp: number
}
